

POST http://localhost:5273/api/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Admin@123!"
}

###

GET http://localhost:5273/api/categories 

###

POST http://localhost:5273/api/categories 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjllYWZlYmVhLTY1OWEtNDRiNi1iODkyLTdkMmU2MTMyNmM3NCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzY4NzI1NjM4LCJpc3MiOiJ5b3VyYXBwLmNvbSIsImF1ZCI6InlvdXJhcHAuY29tIn0.GOqL306G64MDz1IUwYo4EV42Tbofliw-NeH2tKKww-c
Content-Type: application/json

{
  "name": "Beverages"
}

###